### ISSUE TITLE
Add a lang file or themes to choose from

### ISSUE THREAD

**Issue by Alejandro-Sosa** [jmanpenilla/TabTPS#3]
blue is a very good colour but imo pink is even better.

**Comment by jmanpenilla** [comment]
do you mean for the help menu or what?

**Comment by Alejandro-Sosa** [comment]
ah apologies i missed the feature template. well yes mainly the tab action bar since sometimes it blends in with the world but yeah the help menu could be cool aswell.

**Comment by jmanpenilla** [comment]
Themes and translations implemented in latest snapshot (added in 0d848d1ed58b45c5b3bb042f1b67495f80a1fcd8)
