### ISSUE TITLE
NumberFormatException on RecordCPUTask

### ISSUE THREAD

**Issue by joex92** [jmanpenilla/TabTPS#4]
using a fork of paper 1.16.4...
In 1.16.3, the plugin worked fine...
now, when the server finish loading, I get this Warning over and over in the console...

```apache
[TabTPS] Plugin TabTPS v1.2.2 generated an exception while executing task 102
java.lang.NumberFormatException: Infinite or NaN
	at java.math.BigDecimal.<init>(Unknown Source) ~[?:?]
	at java.math.BigDecimal.<init>(Unknown Source) ~[?:?]
	at xyz.jpenilla.tabtps.util.CPUUtil.round(CPUUtil.java:46) ~[?:?]
	at xyz.jpenilla.tabtps.util.CPUUtil.getRecentSystemCpuLoad(CPUUtil.java:38) ~[?:?]
	at xyz.jpenilla.tabtps.util.CPUUtil.recordUsage(CPUUtil.java:29) ~[?:?]
	at xyz.jpenilla.tabtps.task.RecordCPUTask.run(RecordCPUTask.java:15) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Yatopia-"6a1db5e"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

Is it maybe something I set wrong? I literally just added the plugin with a brand new server (testing server)

**Comment by jmanpenilla** [comment]
Are you using macOS? This looks similar to an issue that I fixed recently. Try using the latest build from [my ci](https://jenkins.jpenilla.xyz/job/TabTPS/), and let me know if that fixes it.
Also I would advise against using Yatopia, it's known for having data loss and other issues. I would recommend using [Purpur](https://purpur.pl3x.net/downloads/#1.16.4) or [Tuinity](https://github.com/Spottedleaf/Tuinity) instead.

**Comment by joex92** [comment]
Oh wait... is this a MacOS-only issue? if that's the case I don't mind... I was just running a test server to be sure that all the plugins I use work fine on 1.16.4... I'll still check it out with that build to let you know...

**Comment by jmanpenilla** [comment]
Yes this is a macOS only issue as far as I'm aware, but it should be fixed in the dev builds.

**Comment by joex92** [comment]
> Are you using macOS? This looks similar to an issue that I fixed recently. Try using the latest build from [my ci](https://jenkins.jpenilla.xyz/job/TabTPS/), and let me know if that fixes it.
> Also I would advise against using Yatopia, it's known for having data loss and other issues. I would recommend using [Purpur](https://purpur.pl3x.net/downloads/#1.16.4) or [Tuinity](https://github.com/Spottedleaf/Tuinity) instead.

I confirm that the lastest build fixed that problem... just tried again and didn't have that issue again... 👍 t

**Comment by joex92** [comment]
also, thanks for your suggestion... but what kind of data loss? until now I believe I haven't had any issues, as far as I've realized... I'll still give it a try to those other 2, but my main goal is to have better performance and better memory management...

**Comment by jmanpenilla** [comment]
They have had some unsafe patches, like async player data saving, which they had to remove due to player data corruption. Of course there is also this [infamous video](https://www.youtube.com/watch?v=k7AzkFWQXxE), and to be fair that bug was patched, but something like that getting into a release would steer me away from using that software. As far as performance, most of the actual performance benefits Yatopia has over Paper come from Tuinity, not their own patches. Purpur is based on the Tuinity dev/lighting branch, so it includes these optimizations as well.

**Comment by joex92** [comment]
I mean, everyone makes mistakes... judging a team just for 1 mistake (even is was a big one), which was fixed later, is a bit unfair... I was hesitating a bit when I found out Yatopia, I saw that it was relatively new, so I knew it may had bugs when checking out the update history, so I waited a bit until 1.16.3... and so far I've not had any problem or glitches... maybe I'm missing some configuration to do, but it works fine for me... I used Paper before and I noted a better performance with Yatopia... 
I'll make some test with the other forks and see for myself, but for now I'll stick with Yatopia... 
thanks anyways, I'll check the other ones out...

**Comment by jmanpenilla** [comment]
I listed at least two things, not just one, and there are many many more things I could list if I cared to. It's your server that will have a chance of getting corrupted for margin of error performance improvements, not mine.
