### ISSUE TITLE
[Feature Request] Themes / Basic Mode / Permissions / Online Players count.

### ISSUE THREAD

**Issue by CallumlousTV** [jmanpenilla/TabTPS#7]
**Is your feature request related to a problem? Please describe.**
I like the plugin overall but find the colors to vibrant. and would like to customize them
I also find that when I enable the CPU and RAM options that it should have a basic mode and just tell me the actual values.
I also would want admins to be able to see more info than regular players.

**Describe the solution you'd like**
Customizable colors and themes.
Raw Values for CPU/RAM option like: CPU: 50% | RAM: 2.5G/4G instead of CPU: 50% 10% (sys, proc.) | RAM: 1864M/4096MB (max 8192M)
Admins to see TPS/PING/CPU/RAM and normal players just see TPS/PING.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jmanpenilla** [comment]
Please, one feature request per issue, and also please check for duplicate issues.
